TestProj/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestProj.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TestProj/Controllers/MOCKTBLController.cs
using MOCKDAL.Helper;
using MOCKDAL.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestProj.ViewModel;

namespace TestProj.Controllers
{
    public class MOCKTBLController : Controller
    {
        // GET: CustomerList 
        [HttpGet]
        public ActionResult Index()
        {
            List<MOCKTBLViewModel> mTbl = Common.GetEntries().Select(x => new MOCKTBLViewModel { FirstName = x.FirstName, LastName = x.LastName, Id = x.Id, Email = x.Email }).ToList();            
            //ViewBag.MOCKTBLList = mTbl;
            return View(mTbl);
        }
        //[HttpPost]
        //public ActionResult Index(MOCKTBLViewModel cust)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return Json(false, JsonRequestBehavior.DenyGet);
        //    }
        //    MOCKTBL cl = new MOCKTBL
        //    {
        //        FirstName = cust.FirstName,
        //        LastName = cust.LastName,
        //        Email = cust.Email,
        //        Id = cust.Id
        //    };
        //    Common.SaveRecord(cl);
            
        //    return View(cust);
        //}
        [HttpPost]
        public JsonResult UpdateRec(MOCKTBLViewModel cust)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { result = false, Id = 0 }, JsonRequestBehavior.DenyGet);
            }
            MOCKTBL cl = new MOCKTBL
            {
                FirstName = cust.FirstName,
                LastName = cust.LastName, 
                Email = cust.Email,
                Id = cust.Id
            };
            int id= Common.SaveRecord(cl);

            //return View(cust);
            return Json(new { result = true, Id = id }, JsonRequestBehavior.AllowGet);;
        }

        [HttpGet]
        public ActionResult AddNew()
        {
            var cust = new MOCKTBLViewModel();
            ViewBag.Action = "Add";
            return PartialView("Update", cust);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var cust = new MOCKTBLViewModel();
            if (id != 0)
            {
                var c = Common.GetEntryByID(id);
                cust.FirstName = c.FirstName;
                cust.LastName = c.LastName;
                cust.Email = c.Email;
                cust.Id = c.Id;
            }
            ViewBag.Action = "Edit";
            return PartialView("Update", cust);
        }
        
        [HttpPost]
        public JsonResult Delete(int Id)
        {
            bool result = false;

            result = Common.DeleteEntry(Id);

            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

TestProj/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TestProj/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TestProj/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

TestProj/Views/MOCKTBL/Index.cshtml
@model IEnumerable<TestProj.ViewModel.MOCKTBLViewModel>
@{
    //Index
    ViewBag.Title = "Index";
}
<style>
    .btn-create {
        background-color: black;
        color: white;
        font-weight: 600;  
        font-size:16px;          
    }
    .div-create {
        margin:25px 5px 5px 0px;        
        padding: 5px 5px 5px 0px;        
        background-color: black;
        width:10%;
        text-align:left;
    }
    
    a :hover{
        color:aqua;
    }
</style>

<div class="container">

    @*<h3>List</h3><br />*@
   
    <div class="div-create">        
        <p style="text-align:center;height:100%;margin-top:10px;"><a href="#" onclick="AddRecord();" id="update" class="btn-create">Create New</a>  </p>     
    </div>
    <hr />
    <table class="table table-striped table-bordered">
        <tr>

            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Action</th>
        </tr>
       
        @if (Model != null)
        {            
            foreach (var item in Model)
            {
                <tr id="row_@item.Id">
                    <td id="rFN">@item.FirstName</td>
                    <td id="rLN">@item.LastName</td>
                    <td id="rEmail">@item.Email</td>
                    <td><a href="#" onclick="EditRecord(@item.Id);">Edit</a> &nbsp;| <a href="#" onclick="MessageDelete(@item.Id);">&nbsp;Delete</a></td>

                </tr>
            }
        }

    </table>
    <div id="myPopUpModal" class="modal fade">
        <div class="modal-dialog ">
            <div class="modal-content">
                <div class="modal-header">
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                    <h3 class="modal-title">Add New</h3>
                </div>
                <div class="modal-body" id="myPopupModalContent"></div>
            </div>
        </div>
    </div>

    <div id="myPopUpModalDelete" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                    <h3 class="modal-title">Delete</h3>
                </div>
                <div class="modal-body" id="myPopupModalDeleteContent">
                    <h4 style="margin-bottom:10px; color:red;">Are you sure you want to delete this record? </h4>                    
                    <p id="recordDet" style="color:blue; font-size:16px;margin-top:5px;"></p>
                </div>
                <div class="modal-footer" style="text-align:center;">
                    <a href="#" class="btn btn-default" data-dismiss="modal">CANCEL</a>
                    <a href="#" class="btn btn-success" onclick="DeleteRecord()">CONFIRM</a>
                </div>
            </div>            
        </div>
     </div>   
   
    <input type="hidden" id="RecordId" />
</div>

@*@section scripts{*@
    <script>
        
        var AddRecord = function () {
            var url = '/MOCKTBL/AddNew';
            popUpModal(url);            
        }
        var EditRecord = function (ItemId) {            
            var url = '/MOCKTBL/Edit?Id=' + ItemId; 
            $('.modal-title').html("Edit");
            popUpModal(url);
        }
        function popUpModal(url) {
            $('#myPopupModalContent').load(url, function () {
                $('#myPopUpModal').modal("show");
            });
        }

        var MessageDelete = function (Id) {
            var FName = $('#row_' + Id).find('#rFN').text();
            var LName = $('#row_' + Id).find('#rLN').text();
            var Email = $('#row_' + Id).find('#rEmail').text();

            $("#RecordId").val(Id);
            $('#recordDet').html('First Name : ' + FName + '</br> Last Name : ' + LName + '</br> Email : ' + Email);
            $("#myPopUpModalDelete").modal('show');

        }
        var DeleteRecord = function () {
            var recId = $("#RecordId").val();

            $.ajax({
                type: "POST",
                url: "/MOCKTBL/Delete",
                data: { Id: recId },
                success: function (result) {
                    $("#myPopUpModalDelete").modal('hide');
                    $('#row_' + recId).remove();
                }
                })
        }
    </script>
@*}*@

TestProj/Views/Shared/Update.cshtml
@model TestProj.ViewModel.MOCKTBLViewModel
@{
    ViewBag.Title = "Update";
    var action = ViewBag.Action;
}
<style>
    .txt {
        margin-bottom: 10px;
        width: 100%;
    }
    .err{
       padding-left:2px;
       font-size:12px;
    }
        
</style>
<div>
    <form id="myForm">
        @Html.HiddenFor(m => m.Id)
        <input type="hidden" id="action" value="@action" />
        <div class="row">
            <div class="col-md-12">                 
                @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control txt", @placeholder = "First Name *",@id="uFName" })                             
                @*@Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "text-danger" })*@
                <p id="FNError" class="text-danger err" style="display:none"></p>
                
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                @Html.TextBoxFor(m => m.LastName, new { @class = "form-control txt", @placeholder = "Last Name", @id="uLName" })
                @*@Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })*@

            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control txt", @placeholder = "Email" , @id="uEmail"})
                @*@Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })*@
                <p id="EmError" class="text-danger err" style="display:none"></p>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-12" style="text-align:center">
                <a href="#" id="btnSubmit" class="btn btn-success" style="width:30%;"><b>SAVE</b></a>
            </div>
        </div>

    </form>
</div>

<script>

    $(document).on("click", "#btnSubmit", function (e) {
        e.preventDefault();

        //showErrMessages();

        var myformdata = $("#myForm").serialize();
       
        $.ajax({

            type: "POST",
            url: "/MOCKTBL/UpdateRec",
            data: myformdata,
            success: function (result) {
                if (result.result) {

                    $("#myPopUpModal").modal("hide");
                    UpdateValues(result.Id);
                    //window.location.href = "/MOCKTBL/Index";
                }
                else {
                    alert("message");
                    showErrMessages()
                }
            },
            error: function () {
                alert('error');
            }

        })
    });

    function showErrMessages() {
        if ($('#uFName').val().length == 0) {
            $('#FNError').text("Please enter First name");
            $('#FNError').css('display', 'block');
        }

        if ($('#uEmail').val().length > 0)
        {
            //alert("text");
            var regPattern = /^\b[A-Z0-9._%-]+@@[A-Z0-9.-]+\.[A-Z]{2,4}\b$/;
            if (!regPattern.test($('#Email').val())) {
                $('#EmError').text("Please enter a valid email");
                $('#EmError').css('display', 'block');
            }
        }
    }
    function hideErrMessages() {
        $('#FNError').css('display', 'none');
        $('#EmError').css('display', 'none');
    }

    function UpdateValues(Id) {
        var action = $('#action').val();

        if (action == "Add") {
            var tbl = $('table tbody');
            var newRow = '<tr id="row_"' + Id + '><td>' + $('#uFName').val() + '</td> <td> ' + $('#uLName').val() + '</td> <td>' + $('#uEmail').val() + '</td><td><a href="#" onclick="EditRecord(' + Id + ');">Edit</a> &nbsp;| <a href="#" onclick="MessageDelete(' + Id + ');">&nbsp;Delete</a></td></tr>';
            //alert("new Row " + newRow);
            tbl.append(newRow);
        }
        else if (action == "Edit") {
            var row = '#row_' + Id;           
            $(row).find('#rFN').html($('#uFName').val());
            $(row).find('#rLN').html($('#uLName').val());
            $(row).find('#rEmail').html($('#uEmail').val());
        }
    }

    $(document).ready(function () {
        hideErrMessages();
    })
</script>

TestProj/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Test project</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Customer List", "Index", "MOCKTBL", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>